### ISSUE TITLE
Create Side navigation

### ISSUE THREAD

**Issue by Surafeljava** [Surafeljava/Corporate_chat#2]
Creating the side navigation
- Create the state
- Create the navigation to sample pages

**Comment by srikharshashi** [comment]
Hey! I found this via https://goodfirstissues.com/  can I work on this?

**Comment by Surafeljava** [comment]
![image](https://user-images.githubusercontent.com/34341576/120903125-fc70d800-c64c-11eb-8402-feda4008b8db.png)
![image](https://user-images.githubusercontent.com/34341576/120903132-085c9a00-c64d-11eb-85ff-e865d15f9a6c.png)

**Comment by Surafeljava** [comment]
![image](https://user-images.githubusercontent.com/34341576/120922645-0b9a6900-c6d3-11eb-96ea-dd2c78ce9b04.png)

**Comment by Surafeljava** [comment]
![image](https://user-images.githubusercontent.com/34341576/120922650-18b75800-c6d3-11eb-8208-2a800f75aee8.png)
